-- Gerado automaticamente por scripts/generate-seed.mjs a partir de seed/data/arcanas.json
-- Não editar manualmente.

INSERT OR IGNORE INTO arcanas (name, domain, merge_effect, dismiss_effect, special_rule) VALUES ('Arcano da Espada', 'conquista, heroísmo, liderança', 'Seus ataques causam 5 pontos de dano adicionais e todo dano causado por seus ataques perde seu tipo e não pode receber um tipo enquanto você estiver fundido a este Arcano (portanto, não são afetados por Afinidades a dano).
Ao fazer um ataque, você pode conceder a propriedade multi (qualquer quantidade de alvos) a ele. Caso faça isso, este Arcano é dispensado automaticamente após o ataque ser resolvido (não é considerado uma dispensa voluntária).', NULL, NULL);
INSERT OR IGNORE INTO arcanas (name, domain, merge_effect, dismiss_effect, special_rule) VALUES ('Arcano da Forja', 'calor, fogo, metal', 'Você tem Resistência a dano de fogo.
Todo dano de fogo causado por você ignora Resistências.', 'Ao dispensar este Arcano, escolha Forja ou Inferno:
Forja. Você cria uma arma, armadura ou escudo básicos à sua escolha (veja as páginas 130-133). Um item criado anteriormente desaparece se você usar esta opção de novo. Se você criar uma arma dessa maneira, ela causa dano de fogo em vez de dano físico.
Inferno. Escolha um número qualquer de criaturas que possa ver; você causa 30 pontos de dano de fogo em cada uma delas (esse dano ignora Resistências).', NULL);
INSERT OR IGNORE INTO arcanas (name, domain, merge_effect, dismiss_effect, special_rule) VALUES ('Arcano da Geada', ' frio, gelo, silêncio', 'Você tem Resistência a dano de gelo e é imune a enfurecido.
Todo dano de gelo causado por você ignora Resistências.', 'Era do Gelo. Escolha um número qualquer de criaturas que possa ver; você causa 30 pontos de dano de gelo em cada uma delas (esse dano ignora Resistências).', NULL);
INSERT OR IGNORE INTO arcanas (name, domain, merge_effect, dismiss_effect, special_rule) VALUES ('Arcano da Roda', 'destino, tempo, velocidade', 'Você é imune a lento.
Sua Defesa aumenta em +1.', 'Congelar o Tempo. Escolha um número qualquer de criaturas que você possa ver; cada uma fica lenta. Se uma criatura escolhida dessa forma já estiver lenta, em vez disso, ela fará uma ação a menos durante seu próximo turno (mínimo de zero ações).', NULL);
INSERT OR IGNORE INTO arcanas (name, domain, merge_effect, dismiss_effect, special_rule) VALUES ('Arcano da Torre', 'julgamento, proteção, sacrifício', 'Ao invocar este Arcano, escolha um tipo de dano: ar, fogo, gelo, raio, terra ou trevas. Até que este Arcano seja dispensado, cada aliado seu em cena tem Resistência ao tipo de dano escolhido (você não recebe esta Resistência).', 'Julgamento. Escolha um número qualquer de criaturas que você possa ver; você causa 30 pontos de dano de luz em cada uma delas (esse dano ignora Resistências).', NULL);
INSERT OR IGNORE INTO arcanas (name, domain, merge_effect, dismiss_effect, special_rule) VALUES ('Arcano do Carvalho', 'plantas, terra, veneno', 'Você tem Resistência a dano de terra e de veneno e é imune a envenenado.
Sempre que recuperar PV, você recupera 5 PV adicionais.', 'Florescer. Escolha um número qualquer de criaturas que você possa ver (inclusive a si mesmo); cada uma perde a condição envenenada e recupera 40 PV. Se você estiver no 20° nível ou acima, essa quantidade aumenta para 50 PV; se estiver no 40° nível ou acima, essa quantidade aumenta para 60 PV.', NULL);
INSERT OR IGNORE INTO arcanas (name, domain, merge_effect, dismiss_effect, special_rule) VALUES ('Arcano do Céu', 'chuva, névoa, tempestades', 'Você tem Resistência a dano de ar e de raio.
Você pode usar uma ação para descobrir as condições climáticas do próximo dia em uma área com raio de dois dias de Viagem — o mestre deve responder com informações verdadeiras.', 'Tempestade. Escolha um número qualquer de criaturas que você possa ver; você causa 30 pontos de dano de raio em cada uma delas (esse dano ignora Resistências).', NULL);
INSERT OR IGNORE INTO arcanas (name, domain, merge_effect, dismiss_effect, special_rule) VALUES ('Arcano do Grimório', 'ompreensão, conhecimento, revelações', 'Você sabe ler, escrever, falar e entender todos os idiomas.
Seu dado de Astúcia é considerado um passo maior (máximo d12).', 'Oráculo. Faça uma única pergunta ao mestre; ele deve responder com sinceridade, descrevendo a visão que o Grimório lhe mostrou.
Depois de usado, este efeito de dispensar só volta a ficar disponível na manhã seguinte. Além disso, a mesma pergunta nunca pode ser feita mais de uma vez. O mestre tem a palavra final sobre quais perguntas são similares demais para serem refeitas.', NULL);
INSERT OR IGNORE INTO arcanas (name, domain, merge_effect, dismiss_effect, special_rule) VALUES ('Arcano do Portão', 'espaço, vazio, viagens', 'Você tem Resistência a dano de trevas.
Sua Defesa Mágica aumenta em +1.', 'Ao dispensar este Arcano, escolha Oblívio ou Translocar:
Oblívio. Escolha um número qualquer de criaturas que você possa ver; você causa 30 pontos de dano de trevas em cada uma delas (esse dano ignora Resistências).Translocar. Você e até cinco outras criaturas voluntárias são teletransportados para um local que você já visitou em até 1 dia de Viagem.', NULL);
