-- Gerado automaticamente por scripts/generate-seed.mjs a partir de seed/data/job_powers.json
-- Não editar manualmente.

INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Andarilho'), (SELECT id FROM job_powers WHERE name = 'CAÇADOR DE TESOUROS'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Andarilho'), (SELECT id FROM job_powers WHERE name = 'COMPANHEIRO FIEL'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Andarilho'), (SELECT id FROM job_powers WHERE name = 'PAPO DE TAVERNA'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Andarilho'), (SELECT id FROM job_powers WHERE name = 'PRÁTICO'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Andarilho'), (SELECT id FROM job_powers WHERE name = 'VIAJANTE EXPERIENTE'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Arcanista'), (SELECT id FROM job_powers WHERE name = 'ARCANISMO RITUALISTA'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Arcanista'), (SELECT id FROM job_powers WHERE name = 'ARCANO EMERGENCIAL'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Arcanista'), (SELECT id FROM job_powers WHERE name = 'CÍRCULO ARCANO'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Arcanista'), (SELECT id FROM job_powers WHERE name = 'REGENERAÇÃO ARCANA'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Arcanista'), (SELECT id FROM job_powers WHERE name = 'VINCULAR E INVOCAR'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Atirador'), (SELECT id FROM job_powers WHERE name = 'BARRAGEM'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Atirador'), (SELECT id FROM job_powers WHERE name = 'FOGO CRUZADO'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Atirador'), (SELECT id FROM job_powers WHERE name = 'MAESTRIA COM ARMAS À DISTÂNCIA'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Atirador'), (SELECT id FROM job_powers WHERE name = 'OLHOS DE ÁGUIA'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Atirador'), (SELECT id FROM job_powers WHERE name = 'TIRO DE AVISO'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Elementalista'), (SELECT id FROM job_powers WHERE name = 'ARTILHARIA MÁGICA'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Elementalista'), (SELECT id FROM job_powers WHERE name = 'CATACLISMO'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Elementalista'), (SELECT id FROM job_powers WHERE name = 'ELEMENTALISMO RITUALISTA'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Elementalista'), (SELECT id FROM job_powers WHERE name = 'LÂMINA MÁGICA'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Elementalista'), (SELECT id FROM job_powers WHERE name = 'MAGIA ELEMENTAL'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Entropista'), (SELECT id FROM job_powers WHERE name = 'ABSORVER PM'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Entropista'), (SELECT id FROM job_powers WHERE name = 'ENTROPISMO RITUALISTA'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Entropista'), (SELECT id FROM job_powers WHERE name = 'MAGIA ENTRÓPICA'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Entropista'), (SELECT id FROM job_powers WHERE name = 'SETE DA SORTE'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Entropista'), (SELECT id FROM job_powers WHERE name = 'TEMPO ROUBADO'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Erudito'), (SELECT id FROM job_powers WHERE name = 'ANÁLISE RÁPIDA'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Erudito'), (SELECT id FROM job_powers WHERE name = 'CONCENTRADO'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Erudito'), (SELECT id FROM job_powers WHERE name = 'CONHECIMENTO É PODER'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Erudito'), (SELECT id FROM job_powers WHERE name = 'LAMPEJO DE SABER'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Erudito'), (SELECT id FROM job_powers WHERE name = 'MEMÓRIA TREINADA'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Espiritualista'), (SELECT id FROM job_powers WHERE name = 'ESPIRITUALISMO RITUALISTA'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Espiritualista'), (SELECT id FROM job_powers WHERE name = 'MAGIA DE SUPORTE'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Espiritualista'), (SELECT id FROM job_powers WHERE name = 'MAGIA ESPIRITUAL'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Espiritualista'), (SELECT id FROM job_powers WHERE name = 'PODER CURATIVO'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Espiritualista'), (SELECT id FROM job_powers WHERE name = 'VISMAGUS'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Furioso'), (SELECT id FROM job_powers WHERE name = 'ADRENALINA'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Furioso'), (SELECT id FROM job_powers WHERE name = 'ESPÍRITO INDOMÁVEL'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Furioso'), (SELECT id FROM job_powers WHERE name = 'FRENESI'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Furioso'), (SELECT id FROM job_powers WHERE name = 'PROVOCAR'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Furioso'), (SELECT id FROM job_powers WHERE name = 'RESISTIR'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Guardião'), (SELECT id FROM job_powers WHERE name = 'DUPLO ESCUDEIRO'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Guardião'), (SELECT id FROM job_powers WHERE name = 'FORTALEZA'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Guardião'), (SELECT id FROM job_powers WHERE name = 'GUARDA-COSTAS'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Guardião'), (SELECT id FROM job_powers WHERE name = 'MAESTRIA DEFENSIVA'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Guardião'), (SELECT id FROM job_powers WHERE name = 'PROTEGER'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Guerreiro Sombrio'), (SELECT id FROM job_powers WHERE name = 'AGONIA'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Guerreiro Sombrio'), (SELECT id FROM job_powers WHERE name = 'CORAÇÃO DA ESCURIDÃO'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Guerreiro Sombrio'), (SELECT id FROM job_powers WHERE name = 'GOLPE DAS SOMBRAS'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Guerreiro Sombrio'), (SELECT id FROM job_powers WHERE name = 'LIÇÃO DOLOROSA'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Guerreiro Sombrio'), (SELECT id FROM job_powers WHERE name = 'SANGUE DAS TREVAS'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Inventor'), (SELECT id FROM job_powers WHERE name = 'CHUVA DE POÇÕES'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Inventor'), (SELECT id FROM job_powers WHERE name = 'ENGENHOCAS'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Inventor'), (SELECT id FROM job_powers WHERE name = 'FÓRMULA SECRETA'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Inventor'), (SELECT id FROM job_powers WHERE name = 'ITEM EMERGENCIAL'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Inventor'), (SELECT id FROM job_powers WHERE name = 'VISIONÁRIO'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Ladino'), (SELECT id FROM job_powers WHERE name = 'ALTA VELOCIDADE'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Ladino'), (SELECT id FROM job_powers WHERE name = 'ESQUIVA'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Ladino'), (SELECT id FROM job_powers WHERE name = 'GOLPE BAIXO'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Ladino'), (SELECT id FROM job_powers WHERE name = 'ROUBO DE ALMA'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Ladino'), (SELECT id FROM job_powers WHERE name = 'VEJO VOCÊ MAIS TARDE'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mestre de Armas'), (SELECT id FROM job_powers WHERE name = 'CHUVA DE LÂMINAS'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mestre de Armas'), (SELECT id FROM job_powers WHERE name = 'CONTRA-ATAQUE'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mestre de Armas'), (SELECT id FROM job_powers WHERE name = 'QUEBRA-OSSOS'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mestre de Armas'), (SELECT id FROM job_powers WHERE name = 'MAESTRIA COM ARMAS CORPO A CORPO'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mestre de Armas'), (SELECT id FROM job_powers WHERE name = 'TRESPASSAR'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Orador'), (SELECT id FROM job_powers WHERE name = 'ALIADO INESPERADO'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Orador'), (SELECT id FROM job_powers WHERE name = 'CONDENAR'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Orador'), (SELECT id FROM job_powers WHERE name = 'CONFIO EM VOCÊ'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Orador'), (SELECT id FROM job_powers WHERE name = 'ENCORAJAR'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Orador'), (SELECT id FROM job_powers WHERE name = 'PERSUASIVO'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Quimerista'), (SELECT id FROM job_powers WHERE name = 'CONSUMIR'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Quimerista'), (SELECT id FROM job_powers WHERE name = 'IMITAÇÃO MÁGICA'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Quimerista'), (SELECT id FROM job_powers WHERE name = 'LÍNGUA DAS FERAS'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Quimerista'), (SELECT id FROM job_powers WHERE name = 'PATOGÊNESE'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Quimerista'), (SELECT id FROM job_powers WHERE name = 'QUIMERISMO RITUALISTA'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Guerreiro Sombrio'), (SELECT id FROM job_powers WHERE name = 'ADVERSIDADE'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Furioso'), (SELECT id FROM job_powers WHERE name = 'ATAQUE PODEROSO'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mestre de Armas'), (SELECT id FROM job_powers WHERE name = 'ATAQUE PODEROSO'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Inventor'), (SELECT id FROM job_powers WHERE name = 'BOLSOS FUNDOS'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Entropista'), (SELECT id FROM job_powers WHERE name = 'COMETA'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Arcanista'), (SELECT id FROM job_powers WHERE name = 'COMPANHEIRO HEROICO'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Guerreiro Sombrio'), (SELECT id FROM job_powers WHERE name = 'DESALMADO'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Quimerista'), (SELECT id FROM job_powers WHERE name = 'DOMÍNIO QUIMÉRICO'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Arcanista'), (SELECT id FROM job_powers WHERE name = 'ECOS ARCANOS'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Espiritualista'), (SELECT id FROM job_powers WHERE name = 'ESPERANÇA'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Elementalista'), (SELECT id FROM job_powers WHERE name = 'FEITIÇO PODEROSO'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Entropista'), (SELECT id FROM job_powers WHERE name = 'FEITIÇO PODEROSO'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Espiritualista'), (SELECT id FROM job_powers WHERE name = 'FEITIÇO PODEROSO'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Quimerista'), (SELECT id FROM job_powers WHERE name = 'FEITIÇO PODEROSO'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mestre de Armas'), (SELECT id FROM job_powers WHERE name = 'GOLPE TEMPESTUOSO'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Guardião'), (SELECT id FROM job_powers WHERE name = 'IMBATÍVEL'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Arcanista'), (SELECT id FROM job_powers WHERE name = 'IMUNIDADE À CONDIÇÃO'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Erudito'), (SELECT id FROM job_powers WHERE name = 'MATEMÁGICA'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Furioso'), (SELECT id FROM job_powers WHERE name = 'MÃO DE GORILA'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Inventor'), (SELECT id FROM job_powers WHERE name = 'MELHORIA'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Atirador'), (SELECT id FROM job_powers WHERE name = 'MIRA PERFEITA'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Guardião'), (SELECT id FROM job_powers WHERE name = 'MURALHA'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Ladino'), (SELECT id FROM job_powers WHERE name = 'PILHAR'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Erudito'), (SELECT id FROM job_powers WHERE name = 'PREVISÍVEL!'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Orador'), (SELECT id FROM job_powers WHERE name = 'REPETIÇÃO'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Arcanista'), (SELECT id FROM job_powers WHERE name = 'REVELAÇÃO'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Orador'), (SELECT id FROM job_powers WHERE name = 'RETÓRICA DESARMANTE'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Ladino'), (SELECT id FROM job_powers WHERE name = 'SUMIR'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Atirador'), (SELECT id FROM job_powers WHERE name = 'TIRO PODEROSO'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Elementalista'), (SELECT id FROM job_powers WHERE name = 'VULCÃO'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Lâmina Carmesim'), (SELECT id FROM job_powers WHERE name = 'ARSENAL VERMELHO'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Lâmina Carmesim'), (SELECT id FROM job_powers WHERE name = 'DOBRAR SANGUE'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Lâmina Carmesim'), (SELECT id FROM job_powers WHERE name = 'ESCUDO ESCARLATE'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Lâmina Carmesim'), (SELECT id FROM job_powers WHERE name = 'FRENESI SANGUINOLENTO'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Lâmina Carmesim'), (SELECT id FROM job_powers WHERE name = 'HEMOFAGIA'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Lâmina Carmesim'), (SELECT id FROM job_powers WHERE name = 'INSTINTO ASSASSINO'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Gourmet'), (SELECT id FROM job_powers WHERE name = 'GARFO E FACA'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Gourmet'), (SELECT id FROM job_powers WHERE name = 'COZINHEIRO VIAJANTE'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Gourmet'), (SELECT id FROM job_powers WHERE name = 'CULINÁRIA'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Gourmet'), (SELECT id FROM job_powers WHERE name = 'FEITO COM AMOR'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Gourmet'), (SELECT id FROM job_powers WHERE name = 'SAL E PIMENTA'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Gourmet'), (SELECT id FROM job_powers WHERE name = 'ESPECIALIDADE DA CASA'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Floralista'), (SELECT id FROM job_powers WHERE name = 'Árvore da Vida'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Floralista'), (SELECT id FROM job_powers WHERE name = 'Cloromancia'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Floralista'), (SELECT id FROM job_powers WHERE name = 'Enxerto'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Floralista'), (SELECT id FROM job_powers WHERE name = 'Influência Verdejante'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Floralista'), (SELECT id FROM job_powers WHERE name = 'Jardinagem Marcial'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Gourmet'), (SELECT id FROM job_powers WHERE name = 'Cozinheiro Viajante'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Gourmet'), (SELECT id FROM job_powers WHERE name = 'Culinária'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Gourmet'), (SELECT id FROM job_powers WHERE name = 'Feito com Amor'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Gourmet'), (SELECT id FROM job_powers WHERE name = 'Garfo e Faca'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Gourmet'), (SELECT id FROM job_powers WHERE name = 'Sal e Pimenta'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Invocador'), (SELECT id FROM job_powers WHERE name = 'Cascata'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Invocador'), (SELECT id FROM job_powers WHERE name = 'Expandir Manancial'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Invocador'), (SELECT id FROM job_powers WHERE name = 'Harmonia Elemental'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Invocador'), (SELECT id FROM job_powers WHERE name = 'Invocação'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Invocador'), (SELECT id FROM job_powers WHERE name = 'Invocações Conectadas'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mercador'), (SELECT id FROM job_powers WHERE name = 'Data de Validade'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mercador'), (SELECT id FROM job_powers WHERE name = 'Estoque Pessoal'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mercador'), (SELECT id FROM job_powers WHERE name = 'Já Ouvi Falar'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mercador'), (SELECT id FROM job_powers WHERE name = 'Ventos do Comércio'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mercador'), (SELECT id FROM job_powers WHERE name = 'Verdadeiro Tesouro'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mutante'), (SELECT id FROM job_powers WHERE name = 'Alma Quimérica'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Quimerista'), (SELECT id FROM job_powers WHERE name = 'Alma Quimérica'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Atirador'), (SELECT id FROM job_powers WHERE name = 'Caçador Silencioso'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Ladino'), (SELECT id FROM job_powers WHERE name = 'Caçador Silencioso'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mestre de Armas'), (SELECT id FROM job_powers WHERE name = 'Caçador Silencioso'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Floralista'), (SELECT id FROM job_powers WHERE name = 'Cloromancia Maior'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Andarilho'), (SELECT id FROM job_powers WHERE name = 'Cochilo Poderoso'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Guardião'), (SELECT id FROM job_powers WHERE name = 'Cochilo Poderoso'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mercador'), (SELECT id FROM job_powers WHERE name = 'Cochilo Poderoso'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Andarilho'), (SELECT id FROM job_powers WHERE name = 'Conjuração Maromba'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Esper'), (SELECT id FROM job_powers WHERE name = 'Conjuração Maromba'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Furioso'), (SELECT id FROM job_powers WHERE name = 'Conjuração Maromba'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Guerreiro Sombrio'), (SELECT id FROM job_powers WHERE name = 'Conjuração Maromba'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Quimerista'), (SELECT id FROM job_powers WHERE name = 'Conjuração Maromba'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Floralista'), (SELECT id FROM job_powers WHERE name = 'Dedo Verde'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Erudito'), (SELECT id FROM job_powers WHERE name = 'Dosagem Precisa'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Gourmet'), (SELECT id FROM job_powers WHERE name = 'Dosagem Precisa'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Inventor'), (SELECT id FROM job_powers WHERE name = 'Dosagem Precisa'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mercador'), (SELECT id FROM job_powers WHERE name = 'Dosagem Precisa'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Gourmet'), (SELECT id FROM job_powers WHERE name = 'Especialidade da Casa'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Comandante'), (SELECT id FROM job_powers WHERE name = 'Golpe Valente'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Furioso'), (SELECT id FROM job_powers WHERE name = 'Golpe Valente'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Guardião'), (SELECT id FROM job_powers WHERE name = 'Golpe Valente'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mestre de Armas'), (SELECT id FROM job_powers WHERE name = 'Golpe Valente'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Piloto'), (SELECT id FROM job_powers WHERE name = 'Golpe Valente'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Andarilho'), (SELECT id FROM job_powers WHERE name = 'Lado a Lado'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Esper'), (SELECT id FROM job_powers WHERE name = 'Levanta a Cabeça!'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Orador'), (SELECT id FROM job_powers WHERE name = 'Levanta a Cabeça!'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Virtuoso'), (SELECT id FROM job_powers WHERE name = 'Levanta a Cabeça!'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Entropista'), (SELECT id FROM job_powers WHERE name = 'Luar Purificador'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Espiritualista'), (SELECT id FROM job_powers WHERE name = 'Luar Purificador'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Invocador'), (SELECT id FROM job_powers WHERE name = 'Manancial Interior'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Elementalista'), (SELECT id FROM job_powers WHERE name = 'Manipular Magia'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Entropista'), (SELECT id FROM job_powers WHERE name = 'Manipular Magia'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Invocador'), (SELECT id FROM job_powers WHERE name = 'Manipular Magia'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Simbolista'), (SELECT id FROM job_powers WHERE name = 'Manipular Magia'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Floralista'), (SELECT id FROM job_powers WHERE name = 'Muralha de Espinhos'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Guerreiro Sombrio'), (SELECT id FROM job_powers WHERE name = 'Muralha de Espinhos'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Comandante'), (SELECT id FROM job_powers WHERE name = 'Palavras de Sabedoria'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Erudito'), (SELECT id FROM job_powers WHERE name = 'Palavras de Sabedoria'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Orador'), (SELECT id FROM job_powers WHERE name = 'Palavras de Sabedoria'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Invocador'), (SELECT id FROM job_powers WHERE name = 'Poder dos Cinco Mananciais'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mercador'), (SELECT id FROM job_powers WHERE name = 'Por um Futuro Melhor'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Arcanista'), (SELECT id FROM job_powers WHERE name = 'Refração Auramante'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Espiritualista'), (SELECT id FROM job_powers WHERE name = 'Refração Auramante'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Gourmet'), (SELECT id FROM job_powers WHERE name = 'Rodízio'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Dançarino'), (SELECT id FROM job_powers WHERE name = 'Tranquilidade Efêmera'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Esper'), (SELECT id FROM job_powers WHERE name = 'Tranquilidade Efêmera'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Espiritualista'), (SELECT id FROM job_powers WHERE name = 'Tranquilidade Efêmera'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Ladino'), (SELECT id FROM job_powers WHERE name = 'Tranquilidade Efêmera'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Simbolista'), (SELECT id FROM job_powers WHERE name = 'Tranquilidade Efêmera'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Comandante'), (SELECT id FROM job_powers WHERE name = 'Carga de Cavalaria'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Comandante'), (SELECT id FROM job_powers WHERE name = 'Carruagem Devastadora'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Comandante'), (SELECT id FROM job_powers WHERE name = 'Decreto do Bispo'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Comandante'), (SELECT id FROM job_powers WHERE name = 'Gambito da Dama'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Comandante'), (SELECT id FROM job_powers WHERE name = 'Roque do Rei'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Dançarino'), (SELECT id FROM job_powers WHERE name = 'Dança'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Dançarino'), (SELECT id FROM job_powers WHERE name = 'Dançarino de Guerra'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Dançarino'), (SELECT id FROM job_powers WHERE name = 'Me Acompanhe'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Dançarino'), (SELECT id FROM job_powers WHERE name = 'Sapateado Frenético'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Dançarino'), (SELECT id FROM job_powers WHERE name = 'Troca de Figurino'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Simbolista'), (SELECT id FROM job_powers WHERE name = 'Conexão Simbólica'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Simbolista'), (SELECT id FROM job_powers WHERE name = 'Miragem'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Simbolista'), (SELECT id FROM job_powers WHERE name = 'Simbolismo'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Simbolista'), (SELECT id FROM job_powers WHERE name = 'Símbolos Mágicos'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Simbolista'), (SELECT id FROM job_powers WHERE name = 'Toque Pessoal'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Virtuoso'), (SELECT id FROM job_powers WHERE name = 'Barreira Sonora'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Virtuoso'), (SELECT id FROM job_powers WHERE name = 'Canto da Sereia'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Virtuoso'), (SELECT id FROM job_powers WHERE name = 'Harmonia'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Virtuoso'), (SELECT id FROM job_powers WHERE name = 'Magicanto'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Virtuoso'), (SELECT id FROM job_powers WHERE name = 'Vibrato'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Ladino'), (SELECT id FROM job_powers WHERE name = 'Adepto das Lâminas'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mestre de Armas'), (SELECT id FROM job_powers WHERE name = 'Adepto das Lâminas'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Comandante'), (SELECT id FROM job_powers WHERE name = 'Batalha Incessante'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Elementalista'), (SELECT id FROM job_powers WHERE name = 'Bimagus'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Entropista'), (SELECT id FROM job_powers WHERE name = 'Bimagus'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Espiritualista'), (SELECT id FROM job_powers WHERE name = 'Bimagus'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Dançarino'), (SELECT id FROM job_powers WHERE name = 'Corte Triplo'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mestre de Armas'), (SELECT id FROM job_powers WHERE name = 'Corte Triplo'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Dançarino'), (SELECT id FROM job_powers WHERE name = 'Espetáculo'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Atirador'), (SELECT id FROM job_powers WHERE name = 'Enxame Rodopiante'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Dançarino'), (SELECT id FROM job_powers WHERE name = 'Enxame Rodopiante'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Furioso'), (SELECT id FROM job_powers WHERE name = 'Enxame Rodopiante'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Atirador'), (SELECT id FROM job_powers WHERE name = 'Flecha Dupla'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Comandante'), (SELECT id FROM job_powers WHERE name = 'Flecha Dupla'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Comandante'), (SELECT id FROM job_powers WHERE name = 'Floresta de Ferro'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mestre de Armas'), (SELECT id FROM job_powers WHERE name = 'Floresta de Ferro'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Comandante'), (SELECT id FROM job_powers WHERE name = 'Hoplita'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Guardião'), (SELECT id FROM job_powers WHERE name = 'Hoplita'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Furioso'), (SELECT id FROM job_powers WHERE name = 'Golpe Pulverizador'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Guerreiro Sombrio'), (SELECT id FROM job_powers WHERE name = 'Golpe Pulverizador'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mestre de Armas'), (SELECT id FROM job_powers WHERE name = 'Golpe Pulverizador'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Elementalista'), (SELECT id FROM job_powers WHERE name = 'Guarda Mágica'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Entropista'), (SELECT id FROM job_powers WHERE name = 'Guarda Mágica'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Espiritualista'), (SELECT id FROM job_powers WHERE name = 'Guarda Mágica'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Quimerista'), (SELECT id FROM job_powers WHERE name = 'Guarda Mágica'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Arcanista'), (SELECT id FROM job_powers WHERE name = 'Grande Invocação'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Furioso'), (SELECT id FROM job_powers WHERE name = 'Maré Crescente'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mestre de Armas'), (SELECT id FROM job_powers WHERE name = 'Maré Crescente'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Atirador'), (SELECT id FROM job_powers WHERE name = 'Mira Arcana'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mestre de Armas'), (SELECT id FROM job_powers WHERE name = 'Mira Arcana'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Simbolista'), (SELECT id FROM job_powers WHERE name = 'Mira Arcana'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mestre de Armas'), (SELECT id FROM job_powers WHERE name = 'Momento Fugaz'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Virtuoso'), (SELECT id FROM job_powers WHERE name = 'Música Tema'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Dançarino'), (SELECT id FROM job_powers WHERE name = 'Paso Doble'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Elementalista'), (SELECT id FROM job_powers WHERE name = 'Rituais Ágeis'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Entropista'), (SELECT id FROM job_powers WHERE name = 'Rituais Ágeis'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Espiritualista'), (SELECT id FROM job_powers WHERE name = 'Rituais Ágeis'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Quimerista'), (SELECT id FROM job_powers WHERE name = 'Rituais Ágeis'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Simbolista'), (SELECT id FROM job_powers WHERE name = 'Selos Rituais'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Comandante'), (SELECT id FROM job_powers WHERE name = 'Tábula Rasa'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Furioso'), (SELECT id FROM job_powers WHERE name = 'Teia de Aranha'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mestre de Armas'), (SELECT id FROM job_powers WHERE name = 'Teia de Aranha'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Simbolista'), (SELECT id FROM job_powers WHERE name = 'Tela em Branco'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Atirador'), (SELECT id FROM job_powers WHERE name = 'Tiroteio'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Virtuoso'), (SELECT id FROM job_powers WHERE name = 'Trilha Épica'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Esper'), (SELECT id FROM job_powers WHERE name = 'Dons Psíquicos'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Esper'), (SELECT id FROM job_powers WHERE name = 'Foco Cognitivo'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Esper'), (SELECT id FROM job_powers WHERE name = 'Hipercognição'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Esper'), (SELECT id FROM job_powers WHERE name = 'Navegador'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Esper'), (SELECT id FROM job_powers WHERE name = 'Psicocinese'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mutante'), (SELECT id FROM job_powers WHERE name = 'Acromorfose'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mutante'), (SELECT id FROM job_powers WHERE name = 'Biofagia'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mutante'), (SELECT id FROM job_powers WHERE name = 'Ecdise'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mutante'), (SELECT id FROM job_powers WHERE name = 'Genoclepse'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mutante'), (SELECT id FROM job_powers WHERE name = 'Teriomorfose'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Piloto'), (SELECT id FROM job_powers WHERE name = 'Compressão Tecnológica'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Piloto'), (SELECT id FROM job_powers WHERE name = 'Configuração Flexível'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Piloto'), (SELECT id FROM job_powers WHERE name = 'Coração no Motor'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Piloto'), (SELECT id FROM job_powers WHERE name = 'Pulso Firme'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Piloto'), (SELECT id FROM job_powers WHERE name = 'Veículo Pessoal'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mutante'), (SELECT id FROM job_powers WHERE name = 'Acromorfose Maior'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Piloto'), (SELECT id FROM job_powers WHERE name = 'Bruxa de Aço'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Entropista'), (SELECT id FROM job_powers WHERE name = 'Câmera Lenta'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Ladino'), (SELECT id FROM job_powers WHERE name = 'Câmera Lenta'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Esper'), (SELECT id FROM job_powers WHERE name = 'Campo Psíquico'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Esper'), (SELECT id FROM job_powers WHERE name = 'Descarga de Ondas Mentais'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mutante'), (SELECT id FROM job_powers WHERE name = 'Ecdise Maior'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Atirador'), (SELECT id FROM job_powers WHERE name = 'Isca Chamariz'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Inventor'), (SELECT id FROM job_powers WHERE name = 'Magicanhão Quântico'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mutante'), (SELECT id FROM job_powers WHERE name = 'Mimeoclepse'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Quimerista'), (SELECT id FROM job_powers WHERE name = 'Mimeoclepse'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Inventor'), (SELECT id FROM job_powers WHERE name = 'Nebulização'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Furioso'), (SELECT id FROM job_powers WHERE name = 'Ou Vai ou Racha'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Guerreiro Sombrio'), (SELECT id FROM job_powers WHERE name = 'Ou Vai ou Racha'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Orador'), (SELECT id FROM job_powers WHERE name = 'Pisar no Calo'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Virtuoso'), (SELECT id FROM job_powers WHERE name = 'Pisar no Calo'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Piloto'), (SELECT id FROM job_powers WHERE name = 'Sincronização Dinâmica'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Piloto'), (SELECT id FROM job_powers WHERE name = 'Sobrecarga Explosiva'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Atirador'), (SELECT id FROM job_powers WHERE name = 'Soldado Arcano'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Elementalista'), (SELECT id FROM job_powers WHERE name = 'Soldado Arcano'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mestre de Armas'), (SELECT id FROM job_powers WHERE name = 'Soldado Arcano'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Esper'), (SELECT id FROM job_powers WHERE name = 'Sonho Partido'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Guerreiro Sombrio'), (SELECT id FROM job_powers WHERE name = 'Sonho Partido'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mutante'), (SELECT id FROM job_powers WHERE name = 'Teriomorfose Maior'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Erudito'), (SELECT id FROM job_powers WHERE name = 'Varredura Rápida'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Astrólogo'), (SELECT id FROM job_powers WHERE name = 'Constelação do Boitatá'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Astrólogo'), (SELECT id FROM job_powers WHERE name = 'Constelação do Boto'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Astrólogo'), (SELECT id FROM job_powers WHERE name = 'Constelação do Cão Dourado'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Astrólogo'), (SELECT id FROM job_powers WHERE name = 'Constelação da Rasga-Mortalha'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Astrólogo'), (SELECT id FROM job_powers WHERE name = 'Constelação do Saci'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Bandoleiro'), (SELECT id FROM job_powers WHERE name = 'Cabra da Peste'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Bandoleiro'), (SELECT id FROM job_powers WHERE name = 'Líder de Bando'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Bandoleiro'), (SELECT id FROM job_powers WHERE name = 'Redistribuir Riquezas'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Bandoleiro'), (SELECT id FROM job_powers WHERE name = 'Sertanejo'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Bandoleiro'), (SELECT id FROM job_powers WHERE name = 'Valhacouto'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Carteador'), (SELECT id FROM job_powers WHERE name = 'Altos e Baixos'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Carteador'), (SELECT id FROM job_powers WHERE name = 'Carta Armadilha'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Carteador'), (SELECT id FROM job_powers WHERE name = 'Cartas Mágicas'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Carteador'), (SELECT id FROM job_powers WHERE name = 'Dobro ou Nada'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Carteador'), (SELECT id FROM job_powers WHERE name = 'Mulligan'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Cavaleiro Mágico'), (SELECT id FROM job_powers WHERE name = 'Alma Ferida'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Cavaleiro Mágico'), (SELECT id FROM job_powers WHERE name = 'Coração Ardente'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Cavaleiro Mágico'), (SELECT id FROM job_powers WHERE name = 'Impulso do Coração'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Cavaleiro Mágico'), (SELECT id FROM job_powers WHERE name = 'Magitransformação'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Cavaleiro Mágico'), (SELECT id FROM job_powers WHERE name = 'Transformação Aprimorada'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Forjador de Almas'), (SELECT id FROM job_powers WHERE name = 'Animar Arma'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Forjador de Almas'), (SELECT id FROM job_powers WHERE name = 'Coletar Almas'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Forjador de Almas'), (SELECT id FROM job_powers WHERE name = 'Forjar Característica'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Forjador de Almas'), (SELECT id FROM job_powers WHERE name = 'Forjar Feitiço'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Forjador de Almas'), (SELECT id FROM job_powers WHERE name = 'Manifestar Arma'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Lâmina Carmesim'), (SELECT id FROM job_powers WHERE name = 'Arsenal Vermelho'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Lâmina Carmesim'), (SELECT id FROM job_powers WHERE name = 'Dobrar Sangue'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Lâmina Carmesim'), (SELECT id FROM job_powers WHERE name = 'Escudo Escarlate'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Lâmina Carmesim'), (SELECT id FROM job_powers WHERE name = 'Frenesi Sanguinolento'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Lâmina Carmesim'), (SELECT id FROM job_powers WHERE name = 'Hemofagia'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Malandro'), (SELECT id FROM job_powers WHERE name = 'Engabelar'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Malandro'), (SELECT id FROM job_powers WHERE name = 'Explorar Fraqueza'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Malandro'), (SELECT id FROM job_powers WHERE name = 'Gambiarra'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Malandro'), (SELECT id FROM job_powers WHERE name = 'Golpe Aproveitador'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Malandro'), (SELECT id FROM job_powers WHERE name = 'Jeitinho'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Necromante'), (SELECT id FROM job_powers WHERE name = 'Além do Reino da Morte'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Necromante'), (SELECT id FROM job_powers WHERE name = 'Filhos da Sepultura'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Necromante'), (SELECT id FROM job_powers WHERE name = 'Medo é a Chave'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Necromante'), (SELECT id FROM job_powers WHERE name = 'Por Quem os Sinos Dobram'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Necromante'), (SELECT id FROM job_powers WHERE name = 'Rondó do Pesadelo'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Atirador'), (SELECT id FROM job_powers WHERE name = 'Anatomista'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Erudito'), (SELECT id FROM job_powers WHERE name = 'Anatomista'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Furioso'), (SELECT id FROM job_powers WHERE name = 'Anatomista'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mestre de Armas'), (SELECT id FROM job_powers WHERE name = 'Anatomista'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Bandoleiro'), (SELECT id FROM job_powers WHERE name = 'Cancela do Lampião'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Astrólogo'), (SELECT id FROM job_powers WHERE name = 'Cargas Radiantes'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Entropista'), (SELECT id FROM job_powers WHERE name = 'Ceifeiro do Pesar'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Necromante'), (SELECT id FROM job_powers WHERE name = 'Ceifeiro do Pesar'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Astrólogo'), (SELECT id FROM job_powers WHERE name = 'Constelação da Cruz Austral'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Elementalista'), (SELECT id FROM job_powers WHERE name = 'Corte Infernal'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Guerreiro Sombrio'), (SELECT id FROM job_powers WHERE name = 'Corte Infernal'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Piloto'), (SELECT id FROM job_powers WHERE name = 'Corte Infernal'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Comandante'), (SELECT id FROM job_powers WHERE name = 'Dragão Empalador'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Guerreiro Sombrio'), (SELECT id FROM job_powers WHERE name = 'Dragão Empalador'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Andarilho'), (SELECT id FROM job_powers WHERE name = 'Está Vivo!'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Inventor'), (SELECT id FROM job_powers WHERE name = 'Está Vivo!'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Entropista'), (SELECT id FROM job_powers WHERE name = 'Fagomago'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Gourmet'), (SELECT id FROM job_powers WHERE name = 'Fagomago'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mutante'), (SELECT id FROM job_powers WHERE name = 'Fagomago'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Quimerista'), (SELECT id FROM job_powers WHERE name = 'Fagomago'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Astrólogo'), (SELECT id FROM job_powers WHERE name = 'Fluxo de Yin e Yang'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Elementalista'), (SELECT id FROM job_powers WHERE name = 'Fluxo de Yin e Yang'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Esper'), (SELECT id FROM job_powers WHERE name = 'Fluxo de Yin e Yang'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Dançarino'), (SELECT id FROM job_powers WHERE name = 'Fluxo de Yin e Yang'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Invocador'), (SELECT id FROM job_powers WHERE name = 'Fluxo de Yin e Yang'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Forjador de Almas'), (SELECT id FROM job_powers WHERE name = 'Forja Entrelaçada'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Lâmina Carmesim'), (SELECT id FROM job_powers WHERE name = 'Instinto Assassino'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Erudito'), (SELECT id FROM job_powers WHERE name = 'Lido Como um Livro'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Esper'), (SELECT id FROM job_powers WHERE name = 'Lido Como um Livro'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Ladino'), (SELECT id FROM job_powers WHERE name = 'Lido Como um Livro'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Malandro'), (SELECT id FROM job_powers WHERE name = 'Lido Como um Livro'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Arcanista'), (SELECT id FROM job_powers WHERE name = 'Maestria de Ofuda'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mercador'), (SELECT id FROM job_powers WHERE name = 'Maestria de Ofuda'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Simbolista'), (SELECT id FROM job_powers WHERE name = 'Maestria de Ofuda'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Atirador'), (SELECT id FROM job_powers WHERE name = 'Mestre de Duelos'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Carteador'), (SELECT id FROM job_powers WHERE name = 'Mestre de Duelos'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Furioso'), (SELECT id FROM job_powers WHERE name = 'Mestre de Duelos'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Ladino'), (SELECT id FROM job_powers WHERE name = 'Mestre de Duelos'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mestre de Armas'), (SELECT id FROM job_powers WHERE name = 'Mestre de Duelos'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Forjador de Almas'), (SELECT id FROM job_powers WHERE name = 'Multifunção'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Necromante'), (SELECT id FROM job_powers WHERE name = 'Nascimento da Crueldade'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Malandro'), (SELECT id FROM job_powers WHERE name = 'Papinho Amigável'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Orador'), (SELECT id FROM job_powers WHERE name = 'Papinho Amigável'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Cavaleiro Mágico'), (SELECT id FROM job_powers WHERE name = 'Poder da Amizade'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Carteador'), (SELECT id FROM job_powers WHERE name = 'Preto e Branco'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Entropista'), (SELECT id FROM job_powers WHERE name = 'Preto e Branco'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Espiritualista'), (SELECT id FROM job_powers WHERE name = 'Preto e Branco'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Guerreiro Sombrio'), (SELECT id FROM job_powers WHERE name = 'Preto e Branco'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Necromante'), (SELECT id FROM job_powers WHERE name = 'Pulso das Larvas'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Andarilho'), (SELECT id FROM job_powers WHERE name = 'Raízes Simbióticas'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Floralista'), (SELECT id FROM job_powers WHERE name = 'Raízes Simbióticas'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mutante'), (SELECT id FROM job_powers WHERE name = 'Raízes Simbióticas'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Quimerista'), (SELECT id FROM job_powers WHERE name = 'Raízes Simbióticas'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Bandoleiro'), (SELECT id FROM job_powers WHERE name = 'Redistribuição Aprimorada'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Arcanista'), (SELECT id FROM job_powers WHERE name = 'Rito Proibido'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Carteador'), (SELECT id FROM job_powers WHERE name = 'Rito Proibido'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Arcanista'), (SELECT id FROM job_powers WHERE name = 'Sacrifício Arcano'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Guardião'), (SELECT id FROM job_powers WHERE name = 'Sacrifício Arcano'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Inventor'), (SELECT id FROM job_powers WHERE name = 'Segredo do Grande Caldeirão'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Comandante'), (SELECT id FROM job_powers WHERE name = 'Tática da Asa Quebrada'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Guardião'), (SELECT id FROM job_powers WHERE name = 'Tática da Asa Quebrada'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Atirador'), (SELECT id FROM job_powers WHERE name = 'Truque do Caçador'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Mestre de Armas'), (SELECT id FROM job_powers WHERE name = 'Truque do Caçador'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Carteador'), (SELECT id FROM job_powers WHERE name = 'Vanguarda de Cartas'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Orador'), (SELECT id FROM job_powers WHERE name = 'Voz da Bruxaria'));
INSERT OR IGNORE INTO job_power_jobs (job_id, power_id) VALUES ((SELECT id FROM jobs WHERE name = 'Virtuoso'), (SELECT id FROM job_powers WHERE name = 'Voz da Bruxaria'));
