import { successResponseSchema } from "../../../schemas/common";
import { sessionSchema } from "../../../schemas/session-schemas";
import { npcSummarySchema } from "../../../schemas/npc-schemas";
import { locationSchema } from "../../../schemas/location-schemas";
import { factionBaseSchema } from "../../../schemas/faction-schemas";
import { monsterSummarySchema } from "../../../schemas/monster-schemas";
import { itemSchema } from "../../../schemas/item-schemas";
import { spellSchema } from "../../../schemas/spell-schemas";
import { jobSchema } from "../../../schemas/job-schemas";
import { powerWithJobSchema } from "../../../schemas/power-schemas";
import { arcanaSchema } from "../../../schemas/arcana-schemas";

export const sessionListResponse = successResponseSchema(sessionSchema.array());
export const npcSummaryListResponse = successResponseSchema(npcSummarySchema.array());
export const locationListResponse = successResponseSchema(locationSchema.array());
export const factionListResponse = successResponseSchema(factionBaseSchema.array());
export const monsterSummaryListResponse = successResponseSchema(monsterSummarySchema.array());
export const campaignItemListResponse = successResponseSchema(itemSchema.array());
export const campaignSpellListResponse = successResponseSchema(spellSchema.array());
export const campaignJobListResponse = successResponseSchema(jobSchema.array());
export const campaignPowerListResponse = successResponseSchema(powerWithJobSchema.array());
export const campaignArcanaListResponse = successResponseSchema(arcanaSchema.array());
